### PR TITLE
Update icon for DebugAll

### LINKED ISSUE #137: Update "debug all" icons
There's a new "debug all" icon available in the latest VS Code [release](https://code.visualstudio.com/updates/v1_59#_updated-codicons); we should use that for our "debug/attach all" commands in the application tree view.

### PR DESCRIPTION
**Pull request by pratiksanglikar**
image

Closes #137

### CODE REVIEW

**Comment by philliphoff** [comment]
@pratiksanglikar Should we apply the same treatment to the "debug all" command of a service (which attaches to all replicas of that service)?

**Comment by pratiksanglikar** [comment]
@philliphoff 
I was looking at doing that, but that command is shared with the "debug" command of the replica.
Now, I looked at whether we can condition the icon based on the `when` clause for when it appears at a service level and when it appears at the replica level, but that isn't supported by vscode.
The option to achieve this would be to create a separate command for "debug the replica" and "debug all" at the services level.

I wasn't sure if we want the added complexity just to show a different icon.
If you feel strongly about it, I can add another command.

**Comment by philliphoff** [comment]
We could just define two different commands (for the purposes of specifying the different icons), but actually point the commands to the same command handler during registration (to minimize the logic).  I think that might not be too complex.  What do you think?

**Comment by pratiksanglikar** [comment]
I think that should do the trick!

**Comment by pratiksanglikar** [comment]
New implementation - in addition to the application level `debug-all` icon, a service level icon is also changed to `debug-all`
image

**Review by philliphoff — APPROVED** [review]

**Pull request merged**
